### PR TITLE
Use GitHub Actions

### PR DESCRIPTION
**Pull request by koushiro**

### CODE REVIEW

**Comment by wigy-opensource-developer** [comment]
Do you plan to get the coverage info working on https://codecov.io/gh/multiformats?

**Comment by koushiro** [comment]
@wigy-opensource-developer I have added code coverage measurement to CI, but it need **token** generated by `codecov`.
Please see [actions doc](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets) and [codecov-action usage](https://github.com/codecov/codecov-action#usage) for detail

**Comment by vmx** [comment]
@dignifiedquire any objections merging this one?

**Comment by vmx** [comment]
@koushiro Is there a way to run these GitHub Actions (to see it in action) before merging?

**Comment by koushiro** [comment]
@vmx Maybe you can see the status of my [fork](https://github.com/koushiro/rust-multibase/actions)?

**Comment by koushiro** [comment]
Please add `CODECOV_TOKEN` in the **Settings/Secrets**

**Comment by vmx** [comment]
Done: https://github.com/multiformats/rust-multibase/runs/479540567 Thanks again, that looks really nice.

**Pull request merged**
