### PR TITLE
base256emoji

### PR DESCRIPTION
**Pull request by Jorropo**
See https://github.com/multiformats/multibase/blob/master/rfcs/Base256Emoji.md

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]

**Comment by mriise** [comment]
Correct me if I am wrong @Jorropo 
For rust chars are stored _like_ utf32 on their own (u32), and then get pushed to strings as utf8, but when we decode in rust we can get an iterator over chars (u32) from a utf8 string, so we don't have to convert native utf8 strings into utf32 (then iterate over byte word) to get out a u32 that we can use sensibility.

The whole utf32 section seems more like some recommendations for simple implementation rather than spec necessary.

**Comment by Jorropo** [comment]
>  Do all emojis in the alphabet are insensitive to normalization?

Good question however that would be an issue with the spec if that the case.

I've just checked and yes, none of them modify.

> The RFC for multibase mentions UTF-32 encoding, but the Rust implementation uses UTF-8 even for identity. Could you please clarify how does UTF32 come into picture in the RFC?

The RFC use UTF-32 to not say language specific `[]rune` or `&[char]`. It's describing a canonical implementation where you would first convert whatever you are using (UTF-8 or UTF-16) in UTF-32 *like* (`[]rune` or `&[char]`) and then work on that (or other way around for encoding). (might need clarification in the RFC)
This is particularly inefficient so we use char iterators instead, this is also what the go implementation do.

**Comment by wigy-opensource-developer** [comment]
Awesome. Thanks for all the answers. LGTM

**Comment by mriise** [comment]
ah forgot about no_std, porbably just disable base256 with `#[cfg(feature = "std)]` and set the dep as optional @Jorropo

**Review by vmx — COMMENTED** [review]
LGTM, just the no_std fixes are missing.

**Pull request merged**
